site_name: Curso HVAC Hospitalar
site_description: Curso de aperfeiçoamento em projetos HVAC para Estabelecimentos Assistenciais de Saúde

theme:
  name: material
  language: pt
  palette:
    - scheme: light
      primary: blue
      accent: orange

markdown_extensions:
  - tables
  - toc:
      permalink: true

plugins:
  - search:
      lang: pt

nav:
  - Início: index.md
  - Módulo 0 - Fundamentos Regulatórios: modulo_00.md
  - Módulo 1 - Levantamento de Dados: modulo_01.md
